name: Generate VRT Snapshots
description: Select Xcode version and run PreviewSnapshotTests to generate PNG snapshots

runs:
  using: composite
  steps:
  - name: Select Xcode version
    shell: bash
    run: sudo xcode-select -s '/Applications/Xcode_26.4.app/Contents/Developer'

  - name: Generate snapshots
    shell: bash
    run: |
      set -o pipefail
      xcodebuild -scheme Teloscope test \
        -testPlan VRT \
        | xcbeautify
