name: test

on:
  push:
    branches: [main]
    paths:
      - '**/*.swift'
      - 'Teloscope.xcodeproj/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.swift'
      - 'Teloscope.xcodeproj/**'
      - '.github/workflows/test.yml'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: macos-26
    steps:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md#xcode
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_26.4.app/Contents/Developer'
    - uses: actions/checkout@v6
    - name: test
      run: |
        xcodebuild -scheme Teloscope test | xcbeautify
